// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrlw0cmz31zMNMlrIRBS5s6thgyzktEb8',
    appId: '1:414373887014:web:6a0e44a8acb9107df4fae7',
    messagingSenderId: '414373887014',
    projectId: 'fir-test-d6465',
    authDomain: 'fir-test-d6465.firebaseapp.com',
    storageBucket: 'fir-test-d6465.appspot.com',
    measurementId: 'G-M7DCCYC1KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZOrrRb-F2inCsU4INta2sem3XpxXYVw',
    appId: '1:414373887014:android:c22b4196a06ef077f4fae7',
    messagingSenderId: '414373887014',
    projectId: 'fir-test-d6465',
    storageBucket: 'fir-test-d6465.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiVLouuttOkL4Lw6Pmmp0lrByVvLIJrcs',
    appId: '1:414373887014:ios:c11af2bec8c61cc4f4fae7',
    messagingSenderId: '414373887014',
    projectId: 'fir-test-d6465',
    storageBucket: 'fir-test-d6465.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiVLouuttOkL4Lw6Pmmp0lrByVvLIJrcs',
    appId: '1:414373887014:ios:c11af2bec8c61cc4f4fae7',
    messagingSenderId: '414373887014',
    projectId: 'fir-test-d6465',
    storageBucket: 'fir-test-d6465.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrlw0cmz31zMNMlrIRBS5s6thgyzktEb8',
    appId: '1:414373887014:web:08eb749552908d59f4fae7',
    messagingSenderId: '414373887014',
    projectId: 'fir-test-d6465',
    authDomain: 'fir-test-d6465.firebaseapp.com',
    storageBucket: 'fir-test-d6465.appspot.com',
    measurementId: 'G-ZVV6XL34ZG',
  );
}
